### ISSUE TITLE
import_key error

### ISSUE THREAD

**Issue by ocean00** [xrpinals/XrpinalsMintTool#5]
██╗  ██╗██████╗ ██████╗ ██╗███╗   ██╗ █████╗ ██╗     ███████╗
╚██╗██╔╝██╔══██╗██╔══██╗██║████╗  ██║██╔══██╗██║     ██╔════╝
 ╚███╔╝ ██████╔╝██████╔╝██║██╔██╗ ██║███████║██║     ███████╗
 ██╔██╗ ██╔══██╗██╔═══╝ ██║██║╚██╗██║██╔══██║██║     ╚════██║
██╔╝ ██╗██║  ██║██║     ██║██║ ╚████║██║  ██║███████╗███████║
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚══════╝

[Error]:  Post "": unsupported protocol scheme ""

**Comment by xrpinals** [comment]
Do not use native windows terminal, and Try windows WSL or mingw terminal. 
Git bash is a good choice, please try it.

**Comment by awake2023** [comment]
This is the command executed in the terminal of ubuntu22.04. It was found that this problem occurred due to local compilation.

**Comment by xrpinals** [comment]
``` 
./XrpinalsMintTool import_key --key L5EZftvrYaSudiozVRzTqLcHLNDoVn7H5HSfM9BAN6tMJX8oTWz6

██╗  ██╗██████╗ ██████╗ ██╗███╗   ██╗ █████╗ ██╗     ███████╗
╚██╗██╔╝██╔══██╗██╔══██╗██║████╗  ██║██╔══██╗██║     ██╔════╝
 ╚███╔╝ ██████╔╝██████╔╝██║██╔██╗ ██║███████║██║     ███████╗
 ██╔██╗ ██╔══██╗██╔═══╝ ██║██║╚██╗██║██╔══██║██║     ╚════██║
██╔╝ ██╗██║  ██║██║     ██║██║ ╚████║██║  ██║███████╗███████║
╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝╚══════╝


[Info]:  Private Key of Address 1EUXSxuUVy2PC5enGXR1a3yxbEjNWMHuem imported.

```
This problem cannot be reproduced on ubuntu.
