### ISSUE TITLE
proposal: io/ioutil: move Discard, NopCloser, ReadAll to io #40025

### ISSUE THREAD

**Issue by 0xHoGan** [xrpinals/XrpinalsMintTool#6]
issues : https://github.com/golang/go/issues/40025

io/ioutil, like most things with util in the name, has turned out to be a poorly defined and hard to understand collection of things.

The fileio suggestion is https://github.com/golang/go/issues/19660 for what it's worth.

**Comment by 0xHoGan** [comment]
![Uploading io.png…]()

**Comment by xrpinals** [comment]
Really appreciate with you for this issue, Thank a lot.
